name:                day16
version:             0.1.0.0
github:              "DKurilo/day16"
license:             BSD3
author:              "Dima Kurilo"
maintainer:          "dkurilo@gmail.com"
copyright:           "Dima Kurilo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/DKurilo/day16#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  day16-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day16

tests:
  day16-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day16
